### ISSUE TITLE
Implement format checker

### ISSUE THREAD

**Issue by johnnymetz** [sirosen/check-jsonschema#19]
Would be great to [validate formats](https://python-jsonschema.readthedocs.io/en/stable/validate/#validating-formats). Here's an example of how to use the jsonschema python library to validate a date:

```
from jsonschema import FormatChecker, validate

schema = {
    "title": "Athlete",
    "type": "object",
    "properties": {"birthday": {"type": "string", "format": "date"}},
}

validate({"birthday": "xxx"}, schema, format_checker=FormatChecker())  # raises jsonschema.exceptions.ValidationError
validate({"birthday": "2020-10-20"}, schema, format_checker=FormatChecker())  # works fine
```

**Comment by dudicoco** [comment]
@sirosen thanks for the added feature!

I've tested the new version and it seems to break on of our pre-commit schema validations:
```yaml
- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.6.0
  hooks:
  - id: check-jsonschema
    name: Validate Renovate
    files: ^\.github/renovate\.json
    types:
    - json
    args:
    - --schemafile
    - https://docs.renovatebot.com/renovate-schema.json
```

renovate.json:
```json
{
  "extends": [
    "config:base"
  ],
  "regexManagers": [
    {
      "fileMatch": [
        "(^|/)\\.pre-commit-config\\.yaml$"
      ],
      "matchStrings": [
        "\\nminimum_pre_commit_version: (?<currentValue>.*?)\\n"
      ],
      "depNameTemplate": "pre-commit",
      "datasourceTemplate": "pypi"
    },
    {
      "fileMatch": [
        "(^|/)\\.pre-commit-config\\.yaml$"
      ],
      "matchStrings": [
        "\\n\\s*entry: (?<depName>[^:]+):(?<currentValue>\\S+)"
      ],
      "datasourceTemplate": "docker"
    }
  ]
}
```

Error:
```
Schema validation errors were encountered.
  .github/renovate.json::regexManagers.0.matchStrings.0: '\\nminimum_pre_commit_version: (?<currentValue>.*?)\\n' is not a 'regex'
```
